spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.1.108:3306/test
    username: root
    password: PINGping2@2
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver